.circleci/config.yml, .gitignore, .lando.yml, .lando/scripts/appserver_build.sh, docker-compose.yml, web/sites/default/services.yml
Should let us run tests locally, and scheduled jobs to run against the edge environment.
=> All things around functional tests and services

.lando.yml
Reintroducing this as xdebug won't run without it.
=> Set XDebug mode

.platform.app.yaml, migrate-scripts/migrate.sh
Tee command will flush script output to a dedicated file (overwritten each time) so we can review outside of the general app logs.
=> Enable cron task for migrate script. Script refined for better performance

config/sync/metatag.metatag_defaults.global.yml
Lock file update... can't add direct because GH repo policies.
=> Lock file update

config/sync/domain_path.settings.yml, config/sync/pathauto.settings.yml, web/modules/custom/dept_node/src/Form/NodeForm.php
This, coupled with some rolled back + re-run path aliases, should sort out the inability to save draft nodes.
=> DEPT-190 - some config and group handling

composer.json, composer.lock
Fixes https://www.drupal.org/project/group/issues/3256998
=> Patch group module to restore access to revisions

config/sync/core.extension.yml, config/sync/user.role.authenticated.yml
I've enabled the antibot module in this PR as it threw an error locally when running cim
=> Allow access to admin toolbar for authenticated users

composer.json, composer.lock
NB: this won't automatically pick up changes as the edge build might, but a `composer update 'dof-dss/*'` command as part of any release process would do the trick.
=> Use any version of dept theme package for now

config/sync/views.view.publications_search.yml
Add result heading showing number of publications, trim summaries and strip html, sort by publication date
=> Tweaks to publications search page

config/sync/block.block.pagetitle.yml, config/sync/block.block.pagetitle_banner_top.yml, config/sync/facets_summary.facets_summary.press_releases_summary.yml, config/sync/views.view.consultations_search.yml, config/sync/views.view.news_search.yml, config/sync/views.view.press_release_search.yml, config/sync/views.view.publications_search.yml, web/modules/custom/dept_search/dept_search.module
Add facet summary, fix page title block, add sorting links and css classes for theming
=> Dept-259 press releases search

web/modules/custom/dept_node/dept_node.module
NB: there's enough crossover with RelToAbsUrlsFilter.php to make me think we could do with a service to handle this kind of URL adjustment. The precise return type/end use would still be down to the module/class making use of it, though.
=> Rewrite dept news urls to absolute paths on press releases listing

config/sync/user.role.authenticated.yml, web/modules/custom/dept_core/dept_core.services.yml, web/modules/custom/dept_core/modules/dept_content_processors/src/Plugin/Filter/RelToAbsUrlsFilter.php, web/modules/custom/dept_core/src/Rel2AbsUrl.php, web/modules/custom/dept_node/dept_node.module
Ensures that the source group for a piece of content is linked to from, say, node body (via text filter) or via preprocessed search result row (eg: on press releases when viewed on parent dept; NIGov).
=> Dept 267 service object to encapsulate process to convert relative urls to absolute ones

composer.json, composer.lock, config/sync/block.block.mainnavigation.yml, config/sync/block.block.originstranslation.yml, config/sync/block.block.searchapiform.yml, config/sync/block.block.sitebranding.yml
This patch displays the alias path when adding/editing links through linkit, but still saves the link as the node/xxx path.
=> DEPT-281 LinkIt should show aliased path rather than node id

web/modules/custom/dept_node/dept_node.module
The view mode for the consultations search page has been changed to search_metadata
=> DEPT-223 Update dept_node consultation search code to reflect changes

config/sync/views.view.topic_queue.yml, web/modules/custom/dept_migrate/dept_migrate.services.yml, web/modules/custom/dept_migrate/src/EventSubscriber/PostMigrationFlagSubscriber.php
Bit of overkill for the small number of nodes but should catch these from here on.
=> Dept 325 handle hidden in listings flags

config/sync/block.block.departmentaldetails.yml, config/sync/block.block.departmentaldetails_2.yml, config/sync/block.block.departmentaldetails_3.yml, config/sync/block.block.departmentaldetails_4.yml, config/sync/block.block.departmentaldetails_5.yml, config/sync/block.block.departmentaldetails_6.yml, config/sync/block.block.departmentaldetails_7.yml, config/sync/block.block.mainpagecontent.yml, config/sync/block.block.views_block__block_topics_queue.yml, config/sync/core.entity_view_display.node.topic.teaser.yml, config/sync/core.extension.yml, config/sync/domain_site_settings.domainconfigsettings.yml, config/sync/system.site.yml, config/sync/views.view.frontpage.yml, config/sync/views.view.topic_queue.yml, web/modules/custom/dept_homepage/dept_homepage.info.yml, web/modules/custom/dept_homepage/dept_homepage.routing.yml, web/modules/custom/dept_homepage/src/Controller/HomepageController.php, web/modules/custom/dept_homepage/src/Plugin/Block/FeaturedContentBlock.php
... and adds "Our responsibilities" (topics) block
=> DEPT-340 home page configuration

config/sync/block.block.departmentaldetails.yml, config/sync/block.block.departmentaldetails_2.yml, config/sync/block.block.departmentaldetails_3.yml, config/sync/block.block.departmentaldetails_4.yml, config/sync/block.block.departmentaldetails_5.yml, config/sync/block.block.views_block__links_block_quick_links.yml, config/sync/block.block.views_block__topic_queue_block_topics_queue.yml, config/sync/views.view.links.yml
Links view with block displays for agency links, corporate links and quick links plus draggable view displays for each link type.  Quicklinks block for home page added to block layout.
=> DEPT-339 home page quicklinks

config/sync/block.block.department_details_contact_us.yml, config/sync/block.block.departmentaldetails_5.yml, config/sync/block.block.mainpagecontent.yml, config/sync/block.block.pagetitle.yml, config/sync/block.block.views_block__links_block_agency_links.yml, config/sync/block.block.views_block__links_block_quick_links.yml, config/sync/views.view.links.yml
plus admin links to draggable links views plus other tweaks
=> DEPT-343 "We work with these bodies" (agency links) block

config/sync/block.block.department_details_contact_us.yml, config/sync/block.block.departmentaldetails_2.yml, config/sync/block.block.departmentaldetails_6.yml, config/sync/block.block.mainpagecontent.yml, config/sync/block.block.pagetitle.yml, config/sync/block.block.views_block__links_block_agency_links.yml, config/sync/block.block.views_block__links_block_quick_links.yml, config/sync/core.entity_view_display.department.department.default.yml, config/sync/linkit.linkit_profile.default.yml, config/sync/views.view.contacts.yml
Also added email matcher for the linkit profile
=> DEPT-318 Configure contacts page

config/sync/views.view.news_search.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/src/Plugin/migrate/source/d7/Node.php
- also adding filter to News to exclude unpublished
=> Migration fix

config/sync/block.block.block_our_documents.yml, config/sync/block.block.department_details_contact_us.yml, config/sync/block.block.department_details_management_and_structure.yml, config/sync/block.block.departmental_details_access_info.yml, config/sync/block.block.departmentaldetails_5.yml, config/sync/block.block.niexec_our_documents.yml, config/sync/block.block.views_block__links_block_corporate_links.yml, config/sync/views.view.frontpage_our_documents.yml, config/sync/views.view.links.yml
=> Dept home page "Our documents" blocks and view displays

config/sync/core.entity_view_display.node.news.teaser_with_image.yml, web/modules/custom/dept_homepage/src/Controller/HomepageController.php
I have also updated the title value in the HomepageController to just 'Featured'
=> DEPT-334 Add domain source to news teaser with image display

.platform.app.yaml
As per https://docs.platform.sh/administration/cli/api-tokens.html
=> Update command used to install platform CLI tool

migrate-scripts/sync-db.sh, web/modules/custom/dept_migrate/src/Commands/DeptMigrationCommands.php
Grabs the node references for featured content from the cache table that NIGOV/NI Executive sites' entityqueue seems to be using in D7.
=> Dept 374  nigov executive

config/sync/core.entity_view_display.node.heritage_site.default.yml, config/sync/core.entity_view_display.node.heritage_site.diff.yml, config/sync/core.entity_view_display.node.heritage_site.full.yml, config/sync/field.field.node.heritage_site.field_historic_map_viewer_link.yml, config/sync/field.field.node.heritage_site.field_nismr_link.yml, web/modules/custom/dept_node/dept_node.module
I'm not sure if the code in dept.node.module is the best approach for this, so if anyone has any better ideas, please let me know.
=> DEPT-370 ~ Theme Heritage site pages

config/sync/block.block.views_block__content_by_site_subtopic_related_consultations.yml, config/sync/block.block.views_block__content_by_site_subtopic_related_news.yml, config/sync/block.block.views_block__content_by_site_subtopic_related_publications.yml, config/sync/views.view.content_by_site_subtopic.yml
Adjust content by subtopic view to also show content by topic and ensure blocks are visible on topic and subtopic content types.
=> Related content by topic / subtopic

config/sync/block.block.block_our_documents.yml, config/sync/block.block.department_details_contact_us.yml, config/sync/block.block.department_details_management_and_structure.yml, config/sync/block.block.departmental_details_access_info.yml, config/sync/block.block.departmental_details_social_links.yml, config/sync/block.block.departmentaldetails_2.yml, config/sync/block.block.departmentaldetails_6.yml, config/sync/block.block.mainpagecontent.yml, config/sync/block.block.niexec_featured_topics.yml, config/sync/block.block.niexec_our_documents.yml, config/sync/block.block.searchapiform_search_page.yml, config/sync/block.block.views_block__links_block_agency_links.yml, config/sync/block.block.views_block__links_block_corporate_links.yml, config/sync/block.block.views_block__links_block_quick_links.yml, config/sync/block.block.views_block__news_block_all_depts_latest_press_releases.yml, config/sync/block.block.views_block__topic_queue_block_topics_queue.yml, config/sync/core.entity_view_display.node.consultation.search_result.yml, config/sync/views.view.search.yml
View tweaks for theming purposes. Expose site search form as block so it displays above view header and results.
=> Site search page tweaks

config/sync/core.entity_view_display.node.application.search_result.yml, config/sync/core.entity_view_display.node.article.search_result.yml, config/sync/core.entity_view_display.node.contact.search_result.yml, config/sync/core.entity_view_display.node.landing_page.search_result.yml, config/sync/core.entity_view_display.node.news.search_result.yml, config/sync/core.entity_view_display.node.page.search_result.yml, config/sync/core.entity_view_display.node.profile.search_result.yml, config/sync/core.entity_view_display.node.protected_area.search_result.yml, config/sync/core.entity_view_display.node.publication.search_result.yml, config/sync/core.entity_view_display.node.subtopic.search_result.yml, config/sync/core.entity_view_display.node.topic.search_result.yml, config/sync/core.entity_view_display.node.ual.search_result.yml
35 word trimmed summary for all search result view displays.
Show domain source for news, publications, consultations
=> Search result view displays

config/sync/views.view.content_by_site_subtopic.yml
Adds aggregation (group by) to remove duplicate results and re-adds ordering by title.
=> Fixes for related content view block

config/sync/facets.facet.feed_publication_topics.yml, config/sync/facets.facet.feed_publication_type.yml, config/sync/facets.facet.feed_published_date.yml, config/sync/facets.facet_source.search_api__views_feed__publications_search__pub_feed.yml, config/sync/views.view.publications_search.yml
Config for:
- Views display
- RSS feed display
- Facets for the extra display, mirroring the publications search facets config
- Preprocess code for adjusting the title for the feed icon link
=> DEPT-456 publications feed

config/sync/core.entity_view_display.node.subtopic.topics_teaser.yml
Enable smart trim on output of summary field
=> DEPT-466 fix double html encoding issue in subtopic teaser

web/modules/custom/dept_migrate/src/Commands/DeptMigrationCommands.php
Needs the `node__field_topic_content` table truncated after deployment to clear out the existing duplicates.
=> DEPT-481 only insert new topic content if it's unique

web/modules/custom/dept_topics/css/topic-select.css, web/modules/custom/dept_topics/dept_topics.libraries.yml, web/modules/custom/dept_topics/src/Plugin/Field/FieldWidget/TopicTreeWidget.php
=> Styling for topics select field and button

web/modules/custom/dept_topics/css/topic-select.css, web/modules/custom/dept_topics/dept_topics.libraries.yml, web/modules/custom/dept_topics/js/topic_tree.js, web/modules/custom/dept_topics/src/Form/TopicTreeForm.php, web/modules/custom/dept_topics/src/Plugin/Field/FieldWidget/TopicTreeWidget.php
Styled to look more like chosen select and uses checkboxes for easy de-selection
=> Topic selection behaviour and styling

config/sync/migrate_plus.migration.node_application.yml, config/sync/migrate_plus.migration.node_article.yml, config/sync/migrate_plus.migration.node_consultation.yml, config/sync/migrate_plus.migration.node_gallery.yml, config/sync/migrate_plus.migration.node_landing_page.yml, config/sync/migrate_plus.migration.node_news.yml, config/sync/migrate_plus.migration.node_profile.yml, config/sync/migrate_plus.migration.node_publication.yml, config/sync/migrate_plus.migration.node_subtopic.yml, config/sync/migrate_plus.migration.node_topic.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_application.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_article.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_consultation.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_gallery.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_landing_page.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_news.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_profile.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_publication.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_subtopic.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_topic.yml
source_row_status should be set to 1 for following node types:
- application
- article
- consultation
- gallery
- landing page
- news
- profile
- publication
- subtopic
- topic
=> DEPT-515 Strip html and html entities from summary field values in process pipeline

config/sync/views.view.scheduler_scheduled_content.yml
Keeps the menu output consistent with NIDirect and existing entries from scheduled transitions module
=> Removing unwanted menu entry from this views display

config/sync/core.entity_view_display.node.consultation.search_metadata.yml, config/sync/core.entity_view_display.node.news.search_metadata.yml, config/sync/core.entity_view_display.node.publication.search_metadata.yml, config/sync/views.view.consultations_search.yml, config/sync/views.view.news_search.yml, config/sync/views.view.publications_search.yml
Some tweaks to search result views and the search result with metadata node view modes.  Related PR: https://github.com/dof-dss/nicsdru_dept_theme/pull/160
=> Search results display adjustments

config/sync/facets.facet_source.search_api__views_feed__consultations_search__consultations_feed.yml, config/sync/facets.facet_source.search_api__views_feed__news_search__press_releases_feed.yml, config/sync/facets.facet_source.search_api__views_page__consultations_search__consultations_search.yml, config/sync/facets.facet_source.search_api__views_page__default_search__default_search.yml, config/sync/views.view.consultations_search.yml, config/sync/views.view.news_search.yml, config/sync/views.view.publications_search.yml
Copy approach for publications RSS feed to consultations and news views.
=> DEPT-533 Provide RSS subscribe link on all facetted search pages

config/sync/views.view.media_library.yml
The contextual filter will mean only the requested media types will appear in the selection widget
=> DEPT-557 ~ Add contextual filter to media library widget

config/sync/csp.settings.yml
These changes get rid of the errors - please let me know if they could cause any security issues
=> DEPT-589 ~ Update Content Security Policy

.circleci/config.yml, .lando.yml, .lando/scripts/appserver_build.sh, .lando/scripts/setup-for-dev.sh, web/modules/custom/dept_core/dept_core.module, web/modules/custom/dept_core/dept_core.permissions.yml
Also fixes the npm/nvm installation as per Unity
=> DEPT-568 hide domain form options if user not granted permission

.gitignore, composer.lock, config/sync/core.entity_view_display.node.heritage_site.full.yml, web/themes/custom/nicsdru_dept_theme/inc/preprocess.inc
Easiest to wrap in a field group and follow the lead of the other field(s) and groups on the node display config.
=> DEPT-609 heritage site body field title

composer.lock
Fixes migration import error on node_link migration
=> Version bump for whatlinkshere module

composer.json, composer.lock, config/sync/core.entity_form_display.node.heritage_site.default.yml
- There are some existing visual discrepancies around map controls, likely coming from Claro theme. However, they're already affecting the present version so are not introduced by this update.
- `Fatal error: Cannot redeclare Drupal\address\Plugin\Field\FieldWidget\AddressDefaultWidget::defaultSettings() in /app/web/modules/contrib/address/src/Plugin/Field/FieldWidget/AddressDefaultWidget.php on line 157` requires a container rebuild before the schema update hooks as well as after.
- Functionality looks identical, but this is the preferred release branch and latest version from that.
=> Update address to 2.0.0 and config for form display

config/sync/simple_sitemap.sitemap.communities.yml, config/sync/simple_sitemap.sitemap.daera.yml, config/sync/simple_sitemap.sitemap.default.yml, config/sync/simple_sitemap.sitemap.economy.yml, config/sync/simple_sitemap.sitemap.education.yml, config/sync/simple_sitemap.sitemap.executiveoffice.yml, config/sync/simple_sitemap.sitemap.finance.yml, config/sync/simple_sitemap.sitemap.health.yml, config/sync/simple_sitemap.sitemap.infrastructure.yml, config/sync/simple_sitemap.sitemap.justice.yml, config/sync/simple_sitemap.sitemap.nigov.yml
Attempting to fix the base url (works okay locally... want to avoid wildcard pattern on PSH)
=> Adjust sitemap type configuration

.platform/routes.yaml
www with no dept specified in the hostname should default to the nigov dept site
=> DEPT-701 base URL redirect

config/sync/migrate_plus.migration.node_article.yml, web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_article.yml
what needs a replacing, and when, during the process pipeline
=> Adjust sequence of regex replacements for body content to better suit

config/sync/domain_simple_sitemap.settings.yml
A stopgap while some issues around using domain access are resolved
=> Sitemaps: Use domain source over domain access

composer.json, composer.lock
See https://www.drupal.org/project/filelog/issues/3416342
=> Patch filelog module to fix source of circular reference bug

config/sync/block.block.news_topic.yml, config/sync/block.block.prtopics.yml, config/sync/facets.facet.news_topic.yml, config/sync/search_api.index.news_index.yml
Needs full Solr re-index when deployed
=> Fix news/press-releases facets for topics/global topics filters

web/modules/custom/dept_core/dept_core.module
I'm not sure if this is the correct approach, it is what has been implemented in unity
=> DEPT-780 ~ Add book navigation cache setting

web/modules/custom/dept_core/dept_core.module
Works on regular content save + migrate import/update
=> Set disable_toc flag if the node is a book front-page

web/modules/custom/dept_migrate/modules/dept_migrate_nodes/src/Plugin/migrate/process/BodyFieldProcess.php
Fixes any unadjusted D7 canonical paths for nodes that are sitting in body field content
=> Replace D7 canonical paths with D10 equivalents

config/sync/ultimate_cron.job.dept_sitemap_cron.yml, config/sync/ultimate_cron.job.simple_sitemap_cron.yml
=> DEPT-833 ~ Update cron schedule for sitemap creation

web/modules/custom/dept_homepage/js/normalise_base_url.js
=> DEPT-790 hostname replacement bugfix

web/modules/custom/dept_core/dept_core.libraries.yml, web/modules/custom/dept_core/dept_core.module, web/modules/custom/dept_core/js/main_menu_navigation.js
Tried a smorgasbord of server side options to try and fix this with no definitive solution so as a last option I decided to alter the link in JS.
=> DEPT-868 ~ JS script to transform Home link to span when on homepage

web/modules/custom/dept_core/dept_core.module, web/themes/custom/nicsdru_dept_theme/templates/form/fieldset.html.twig
This will allow descriptions to appear just under the legend in fieldsets on the node edit forms
=> DEPT-907 ~ Override a11y_form_helpers fieldset template

config/sync/filter.format.basic_html.yml
I can't find any reason why span was not included in the allowed html
=> DEPT-916 ~ Add span to allowed html

config/production/domain.config.finance.metatag.metatag_defaults.global.yml, config/sync/domain_config_ui.settings.yml
This was the only way I could find to do this, please let me know if there is anything that will break domain
=> DEPT-925 ~ Move google verification tag to finance domain

web/modules/custom/dept_node/dept_node.module
Add Consultation Pending option for consultations that have not yet started
=> DEPT-952 ~ Add Consultation Pending option

migrate-scripts/migrate.sh, web/sites/default/settings.php
Bugfix due to -ni suffix being used to specify the dept. Fixed now
=> Migrate script override variable and better handling of domain hostname override

composer.json, composer.lock, config/sync/core.entity_view_display.node.consultation.default.yml, config/sync/core.entity_view_display.node.consultation.full.yml, config/sync/domain.config.communities.metatag.metatag_defaults.global.yml, config/sync/metatag.metatag_defaults.global.yml
Fixes a bug where domain exports metatag variants with the same uuid, causing a config import error later down the line.
=> Config import error

config/sync/views.view.publications_search.yml
- Reverts the RSS flag changes to publications search
=> Hotfix: Revert publications feed views config changes

web/sites/default/settings.php
Things for the next DEPT release
=> Remove memory limit on node pages as system limit is higher now (#989)

config/sync/ultimate_cron.job.advban_cron.yml, config/sync/ultimate_cron.job.autoban_cron.yml, config/sync/ultimate_cron.job.field_cron.yml, config/sync/ultimate_cron.job.file_cron.yml, config/sync/ultimate_cron.job.filelog_cron.yml, config/sync/ultimate_cron.job.layout_builder_cron.yml, config/sync/ultimate_cron.job.scheduled_transitions_cron.yml, config/sync/ultimate_cron.job.webform_cron.yml
Used equivalent NIDirect tasks for indicative scheduling times
=> Missed a few config entries

config/sync/core.entity_view_display.node.news.search_metadata.yml, web/modules/custom/dept_search/dept_search.module, web/themes/custom/nicsdru_dept_theme/templates/content/node--search-metadata.html.twig
Domain source seems to be a privileged field value (in terms of access) so we can work around some of the access inconsistencies by handling the values in a preprocess hook and setting the values we want consistently that way
=> Preprocess template variables to work around access issues

config/sync/webform.webform.contact_dard.yml, config/sync/webform.webform.contacting_department.yml, config/sync/webform.webform.feedback.yml, config/sync/webform.webform.truth_recovery_design_panel.yml
- Disable webform submission saving
- Disable Contact DARD and Truth Recovery Design Panel webforms
- Make sure correct '/your-privacy' link in Feedback form
=> DEPT-1086 ~ Update webform config

config/sync/views.view.files.yml
Improves filter by filename, adds explanatory header and smartens up timestamps display.
=> Adjust files view config

web/modules/custom/dept_book/dept_book.module
Not enough to use entity update when transitioning between moderation states
=> Use entity presave hook to trigger toc removal on books

composer.json, composer.lock, config/sync/core.extension.yml
dept_topics has code that references the events this module provides. If you release them together you get a race condition on the events registering and :boom: 
Releasing this first avoids that issue.
=> Add and enable entity_events module ahead of downstream code

config/sync/config_ignore.settings.yml
Avoids UI made changes being overwritten on deployments
=> Ignore webform config

web/themes/custom/nicsdru_dept_theme/inc/preprocess.inc, web/themes/custom/nicsdru_dept_theme/templates/field/field--field-external-publication.html.twig
Remove bullet on list items and add classes to present html icon
=> Adjust external publications field output style
