dof-dss/nicsdru_dept

migrate-scripts/migrate.sh
migrate-scripts/sync-files.sh

Expecting to add to this over time: aliases, redirects etc to follow.
NB: MySQL timeouts on prod cluster mean long running migrations like the files one may need to be batch executed if running from scratch. Incremental updates should be fine.

Add migrate script; drop files sync script

---

.circleci/config.yml

Mostly a rehash/tidy of what's been used before. Needs to execute overnight to help debug any issues with SSH keys or other minor things in there.
The PSH environment is active and up, so if all goes to plan this should build + push back to GH, which in turn triggers the webhook there which prompts PSH to fetch and build/deploy on there.

Dept edge build

---

.gitignore
composer.json
composer.lock

* Getting rid of group_menu_content config and references (content has been purged from prod db to make config import work)
* Moving origins theme into an origins folder, rather than custom, because it's technically shared between builds as a base theme.

Menus tidyup + composer tweaks

---

.platform.app.yaml
migrate-scripts/migrate.sh

Commenting out taxo import (for now) due to some unexpected SQL exceptions thrown during run. These change very infrequently, so likely not too risky at this stage.
Runtime (without d7_files was about 3 mins). With d7_files, it'll potentially be up to 2-3hrs, subject to the number of changes detected along the way.

Tweak migrate script and add cron entry for nightly run

---

migrate-scripts/migrate.sh
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/dept_migrate_group_nodes.services.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/src/EventSubscriber/NodeEntityMigrateSubscriber.php
web/modules/custom/dept_migrate/src/MigrateSupport.php

Fixes for migrate script, too.
Rollout for this will need all migrate modules reinstalled, past group_node_* and group_users migration tables dropped and then a migrate import with --update flag for node_news (at least).
Script takes about 5 mins end to end, with no or few changes. Up to, possibly over, 30 mins for a more comprehensive import or updates.

Make node migrate handler a little more capable of handling failure.

---

config/sync/migrate_plus.migration.redirects.yml
config/sync/migrate_plus.migration_group.migrate_group_redirects.yml
web/modules/custom/dept_migrate/config/install/migrate_plus.migration.redirects.yml
web/modules/custom/dept_migrate/dept_migrate.services.yml
web/modules/custom/dept_migrate/src/EventSubscriber/RedirectMigrateSubscriber.php

Rather than try and wrestle migrate pseudo fields in to break up/rewrite node paths, it's easier to add an event subscriber which can prepare the row before it saves. That can then detect any internal node paths and update the numerical value to the correct D9 version, if it exists.

Add redirects migration and row prepare subscriber event

---

config/sync/core.entity_form_display.node.publication.default.yml
config/sync/core.entity_view_display.node.publication.default.yml
config/sync/core.entity_view_display.node.publication.teaser.yml

Needs drush cim run twice (complains first time, removes the field second time)

Remove publication attachment field (stray config)

---

.platform.app.yaml
config/sync/book.settings.yml
config/sync/core.base_field_override.node.book.promote.yml
config/sync/core.extension.yml
config/sync/migrate_plus.migration.dept_book.yml
config/sync/migrate_plus.migration.node_collection.yml
config/sync/migrate_plus.migration_group.migrate_group_book.yml
migrate-scripts/migrate.sh
web/modules/custom/dept_migrate/config/install/migrate_plus.migration.dept_book.yml
web/modules/custom/dept_migrate/config/install/migrate_plus.migration_group.migrate_group_book.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_collection.yml
web/modules/custom/dept_migrate/src/MigrateUuidLookupManager.php

Importing books and config relies on:
* Book module being enabled
* Collection nodes being imported *first* (they act as the book entity/housing themselves)
* Book migration happening which links together existing nodes (a variety of content types) and allocating them to the Collection nodes from before.
Migrations still suffer from occasional instances where a D7 or D9 node can't be found, for whatever reason. We'll be looking to improve visibility of that in a later feature.

Book module config, collection and book migrate config

---

.circleci/config.yml

Don't perceive this to be a service disclosure risk, as that information is easily derived from PSH public docs around Solr service defaults for Drupal projects and there's little that can be done to access this service from outside the cluster without an authenticated SSH tunnel. Can also store this in Circle CI but the value is then obfuscated even from admin view which takes longer for future debugging.

Add env var for solr host/port on psh

---

.platform.app.yaml
.platform/services.yaml

- Metrics show D7 db size is only at 30% usage - likely due to trimming of unwanted cache tables etc.
- Increase Solr disk space size as we're filling it with much more content now.
- Increase D9 db disk size to accommodate extra content (by recycling the excess from the D7 db service we weren't using)

Double solr disk size, enlarge main db from excess in d7 db

---

config/sync/field.field.node.application.field_site_topics.yml
config/sync/group.role.department_site-anonymous.yml
config/sync/migrate_plus.migration.node_application.yml
config/sync/migrate_plus.migration.node_article.yml
config/sync/migrate_plus.migration.node_consultation.yml
config/sync/migrate_plus.migration.node_contact.yml
config/sync/migrate_plus.migration.node_gallery.yml
config/sync/migrate_plus.migration.node_heritage_site.yml
config/sync/migrate_plus.migration.node_landing_page.yml
config/sync/migrate_plus.migration.node_protected_area.yml
config/sync/migrate_plus.migration.node_publication.yml
config/sync/views.view.press_releases.yml
config/sync/views.view.publications_feed.yml
web/modules/custom/dept_core/dept_core.module
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_application.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_article.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_consultation.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_contact.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_gallery.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_heritage_site.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_landing_page.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_protected_area.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_publication.yml
web/modules/custom/dept_node/dept_node.module

* Migrate config change needed to ensure field_site_subtopic and field_site_topics use node lookups: they're entity reference fields looking for nodes, not taxo terms - that's the global topics field.
* Minor query adjustment needed when adding parent group relationship + filter on a view. We need to set it to the current department/group id which can't be done with the present filter options. This + distinct operator ensures that the results returned for anon + auth users are the same, subject to any node access restrictions, and the group_content_field_data records from the relationship doesn't add duplicate rows where a node sits in multiple groups.

DEPT 62: RSS feeds for publications by topics/subtopics

---

.circleci/config.yml
.environment

See https://docs.platform.sh/guides/drupal9/deploy/customize.html#environment for details.
Also fixes drush commands in Circle CI for rebuilding Solr indexes overnight as prior config couldn't resolve drush as it wasn't on $PATH.

Add .environment file to add vendor/bin to $PATH

---

web/modules/custom/dept_migrate/modules/dept_etgrm/dept_etgrm.install
web/modules/custom/dept_migrate/modules/dept_etgrm/inc/sql_delete_stale_imports.sproc
web/modules/custom/dept_migrate/modules/dept_etgrm/src/Commands/EtgrmCommands.php

A pragmatic approach to drop any rows associated with older bulk update timestamps - we used the `created` timestamp as a kind of batch id; the last one is always stored in the dept_etgrm.data config value.
Occasionally, something doesn't go quite right and it doesn't tidy up the previous bulk update's data before rebuilding resulting in duplicate sets in the group_content tables meaning you get duplicates coming out on the front-end when the underlying queries return multiple values per content item.
So essentially this sproc looks for the most recent timestamp with lots of rows associated with it (over 1k as a baseline), then loops through any others that are older, and removes the rows associated with that timestamp.
We do this at the end of the process of rebuilding the group …

DEPT-189 Tidyup sproc and update hook to install it

---

config/sync/views.view.topic_queue.yml

It's adapted in custom code based on the detected hostname/group so the correct entity queue topics are listed.

Reset entity queue binding in config

---

config/sync/csp.settings.yml

Can enable remote logging once a service is selected and activated. Otherwise, dblog is likely to flood with notices once in production.

DEPT-194 Add extra config from NIDirect, default to disabled logging for now

---

.platform.app.yaml
.platform/services.yaml

Current dev plan states 120GB of free space. We have 99 allocated to the app server, then 10 for D9 db and 10 for D7 db, and now 1 for Solr.

Double the Solr service disk allowance

---

config/sync/facets.facet_source.search_api__views_page__consultations_search__consultations_search.yml
config/sync/facets.facet_source.search_api__views_page__news_search__news_search.yml
config/sync/facets.facet_source.search_api__views_page__press_release_search__pr_search_page.yml
config/sync/facets.facet_source.search_api__views_page__publications_search__publications_search.yml

Also fixes https://digitaldevelopment.atlassian.net/browse/DEPT-233
The facets_pretty_paths module is breaking facets. Tried updating to the latest patch on https://www.drupal.org/project/facets_pretty_paths/issues/3254600 - but no joy.
Disabling facets pretty paths url processor and using the query string processor instead resolves the problem.  The facets pretty paths url processor can be re-enabled when https://www.drupal.org/project/facets_pretty_paths/issues/3254600 is resolved.

DEPT-232: fix WSOD when selecting facets

---

composer.json
composer.lock
config/sync/facets.facet_source.search_api__views_page__news_search__news_search.yml

Drupal.org issues that are related, but clash a little:
* https://www.drupal.org/node/2952005
* https://www.drupal.org/node/3254600
Fixes facet results count, reset/remove link and compatibility with contextual args on views.

Reconcile two clashing d.o. patches into single patch file

---

.circleci/config.yml
.platform.app.yaml
reindex-edge-solr.sh

Takes 50 minutes of CI compute time, Mon-Fri, and runs it on platform.sh's own cron handler to save :moneybag: :moneybag: :moneybag:

Move solr reindex to psh cron

---

.gitignore
.lando/config/drupal.services.yml
.lando/config/drupal.settings.php
.lando/scripts/appserver_build.sh

When the project installs, it'll move two template files into place - one for local settings and one for local services config. To date they've not quite been joined up, but now they should be and it'll make http header + twig template suggestions appear by default for local development + make it easier to adjust.

Fix paths and inclusions for Twig debugging etc when installing project

---

web/modules/custom/dept_node/dept_node.module

Ensures the correct entity queue id is passed in to the view so that the topics are shown at /topics

Negotiate environment when parsing hostname for topic queue id

---

config/sync/core.entity_form_display.node.contact.default.yml
config/sync/core.entity_view_display.node.contact.default.yml
config/sync/core.entity_view_display.node.contact.diff.yml
config/sync/core.entity_view_display.node.contact.full.yml
config/sync/core.entity_view_display.node.contact.search_result.yml
config/sync/core.entity_view_display.node.contact.teaser.yml
config/sync/migrate_plus.migration.node_contact.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_contact.yml

Map field config for display can be adjusted as required - currently set to use Google static map with out of the box defaults.
Heritage site also uses the same maps so probably needs updating, separately.

Update migration mapping for contacts using new map location field

---

web/modules/custom/dept_node/src/ContentTopics.php
web/modules/custom/dept_topics/dept_topics.module

Now that content under subtopics can also reference articles and other subtopics we had to reshuffle how those lists were created. Where there isn't draggableviews data to determine the precise order of things to be returned we fall back to a query that unions articles and subtopics referencing a subtopic and use the results to generate the same result set for the lists we show.

Dept 256  subtopics with articles and other subtopics

---

config/sync/core.entity_view_display.node.heritage_site.full.yml
config/sync/migrate_plus.migration.node_landing_page.yml
web/modules/custom/dept_migrate/modules/dept_migrate_group_nodes/config/install/migrate_plus.migration.node_landing_page.yml
web/modules/custom/dept_node/dept_node.module

Takes the banner image media entity reference from a landing page node matching the same topic - subtopic nodes or those that use the parent topic field differ a little.
Produces a responsive image render element for the banner image in the thin banner style which can be fed into Twig templates as needed.

DEPT-338 Banner images

---

config/sync/block.block.department.yml
config/sync/block.block.prpublicationdate.yml
config/sync/block.block.prtopics.yml
config/sync/facets.facet.pr_department.yml
config/sync/facets.facet.pr_publication_date.yml
config/sync/facets.facet.pr_topics.yml
web/modules/custom/dept_search/dept_search.module

Introduces:
* Block layout page change so that facet blocks now indicate which view they're associated with:
* Review of Solr config files to confirm group related fields are no longer being added to Solr documents.

Dept 304 - block listing improvements for facets

---

composer.json
composer.lock
config/sync/core.entity_form_display.department.department.default.yml
config/sync/core.entity_form_display.node.heritage_site.default.yml
config/sync/core.entity_view_display.node.heritage_site.default.yml
config/sync/core.entity_view_display.node.heritage_site.full.yml
config/sync/core.entity_view_display.node.heritage_site.teaser.yml
config/sync/core.extension.yml
config/sync/field.field.node.heritage_site.field_address.yml
config/sync/field.storage.node.field_address.yml
config/sync/migrate_plus.migration.node_heritage_site.yml
web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_heritage_site.yml
web/modules/custom/dept_migrate/src/AddressFieldMerge.php

* Moves the legacy address field out of sight on the editorial forms but retained for reference if needed in future.
* Replaces the text fields for address parts with a proper address component.
* Integration with geolocation module for accurate and simple geocoding.
* Map widget for address disabled on heritage site, users encouraged to populate the address component fields. Clicking a point on the map geocodes the nearest known address and populates the address component (two-way sync)

DEPT 328 structured address fields

---

web/modules/custom/dept_core/dept_core.module

Some important points about Twig allowed method names config to be aware of, but not of any direct consequence here as I've opted to supply the commonly used dept values as preprocess variable values rather than Department objects

Introduce dept id and name as preprocess variables for use in templates

---

config/sync/block.block.departmental_details_social_links.yml
config/sync/block.block.departmentaldetails_2.yml
config/sync/block.block.departmentaldetails_6.yml
config/sync/block.block.mainpagecontent.yml
config/sync/block.block.niexec_featured_topics.yml
config/sync/block.block.views_block__links_block_quick_links.yml
config/sync/block.block.views_block__news_block_all_depts_latest_press_releases.yml
config/sync/block.block.views_block__topic_queue_block_topics_queue.yml
config/sync/field.field.block_content.block_group.field_blocks.yml
config/sync/structure_sync.data.yml
config/sync/views.view.frontpage_our_documents.yml

Move Budget and PfG blocks out of "Our documents" block and into a new niexec featured topics block that sits below "Our responsibilities" (see https://github.com/dof-dss/nicsdru_dept_theme/pull/87)

niexec home page: move Budget and PfG blocks 

---

web/modules/custom/dept_topics/dept_topics.module

Prevents WSOD when saving nodes that don't have field_site_subtopics

Only try to invalidate caches where a node has the field we're interested in

---

config/sync/block.block.accesstoinformation.yml

Show on topic pages as well as subtopic pages

Visibility settings for accesstoinformation block

---

web/modules/custom/dept_topics/src/ContentTopics.php

We had a similar edge case in subtopic listings where some articles weren't 100% accurate when syncing from D7. TLDR: we'd bring across what we reasonably can, then have site owners adjust/set this before launch after which the issue resolves itself and concentrates technical effort on higher value tasks.

Fallback entity query if topic doesn't have subtopics defined in draggable views

---

config/sync/domain_source.settings.yml

Change domain_source settings so that content sent to all affiliates is viewable on all affiliates and a redirect to the source domain does not occur.
(This is needed for "global" content shared by all domains - e.g. help content: crown copyright, privacy, terms and conditions, etc.)

Disable link rewrites for canonical routes

---

config/sync/core.extension.yml
config/sync/views.view.topics.yml

The "topics_teaser" view mode does not exist for topics (leading to some weirdness in twig templates).  Switch page and block views to using "teaser" view mode for topic output.
Also uninstall quickedit module.  Its deprecated and causes some render problems for topic teasers when it inserts quickedit contextual links

Update topics view and uninstall deprecated quickedit module

---

config/sync/metatag.metatag_defaults.node__application.yml
config/sync/metatag.metatag_defaults.node__article.yml
config/sync/metatag.metatag_defaults.node__publication.yml
config/sync/metatag.settings.yml

Dropping in the global topics as part of the og article:tag output

DEPT-468 ~ Add global topics to metadata for topic child content

---

config/sync/user.role.author.yml
config/sync/user.role.supervisor.yml

Remove perms for authors and supervisors to edit "Page" content type.  Also added "Access content overview" permission to supervisor role.

Update user permissions for editing Page content type

---

config/sync/user.role.admin.yml
config/sync/user.role.author.yml
config/sync/user.role.stats_author.yml
config/sync/user.role.stats_supervisor.yml
config/sync/user.role.supervisor.yml
config/sync/user.role.topic_layout_supervisor.yml
config/sync/user.role.topic_supervisor.yml
web/modules/custom/dept_topics/dept_topics.permissions.yml
web/modules/custom/dept_topics/dept_topics.routing.yml

Prior problem was that stats author (or similar future roles less than full author) roles could not use the topic picker without being given node permissions for topics/subtopics too which wasn't in the brief for those restricted roles.

Adjust topic picker widget to a permission for finer grained control

---

config/sync/migrate_plus.migration.node_consultation.yml
config/sync/migrate_plus.migration.node_publication.yml
web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_consultation.yml
web/modules/custom/dept_migrate/modules/dept_migrate_nodes/config/install/migrate_plus.migration.node_publication.yml

This will set the time portion of the field value to, effectively, an hour behind but with BST offset this normalises the value. Without this, the values are pulled across and stored in UTC but Drupal will apply the localised TZ offset which often moves the rendered day value by 1 making the migration look broken.
These values will likely need to be reverted/reset once BST finishes, if content is still continuing to be migrated. Keeping the site TZ as UTC isn't an option though as scheduled transitions depends on the correct local time being kept.

Set TZ to localised TZ rather than UTC

---

web/modules/custom/dept_topics/dept_topics.services.yml
web/modules/custom/dept_topics/src/EventSubscriber/SolrQueryAlterEventSubscriber.php

Once applied, single topic selections against field_site_topics use the topic manager service to look up the tree and also add parent topics. This ensures that the publications/consultations searches surface content correctly.
Eg:
**Before:**
**After:**

Add event subscriber to listen for/adjust site topics field values on Solr docs

---

config/sync/block.block.preview_placeholder_related_content.yml

There's a content block added on the prod db to match up to this content block, in case you try importing config and it fails :)
This is a quick solution to showing a representation of the actual related content block if you're previewing a node (new or existing content)

Placeholder block for preview aside region

---

web/themes/custom/nicsdru_dept_theme/inc/preprocess.inc

It is now handled in a separate placeholder block and keeping this in produces duplication or errors. The actual block that shows related content links is provided from a views display and is already configured to show, except on the preview path

Drop the programmatically rendered related content block

---

config/sync/migrate_plus.migration.d7_taxonomy_term_chart_type.yml
config/sync/migrate_plus.migration.d7_taxonomy_term_global_topics.yml
config/sync/migrate_plus.migration.d7_taxonomy_term_indicators.yml
config/sync/migrate_plus.migration.d7_taxonomy_term_outcomes.yml
migrate-scripts/migrate.sh
web/modules/custom/dept_migrate/modules/dept_migrate_taxo/config/install/migrate_plus.migration.d7_taxonomy_term_chart_type.yml
web/modules/custom/dept_migrate/modules/dept_migrate_taxo/config/install/migrate_plus.migration.d7_taxonomy_term_global_topics.yml
web/modules/custom/dept_migrate/modules/dept_migrate_taxo/config/install/migrate_plus.migration.d7_taxonomy_term_indicators.yml
web/modules/custom/dept_migrate/modules/dept_migrate_taxo/config/install/migrate_plus.migration.d7_taxonomy_term_outcomes.yml

- Replace needless migrate lookups with fixed values
- turn off content lock modules at start of nightly migration (re-enabled at the end by config import)

Migration taxo issues

---

web/modules/custom/dept_sitemap/dept_sitemap.module

One hit fix for wildcarded hostname pattern in sitemap index column. Reduces processing overhead; previously loading each dept in sequence with update sql command for each.

DEPT-671 Table wide replace pattern

---

web/modules/custom/dept_sitemap/dept_sitemap.module

Existing cron query failed due to problems escaping the REPLACE() expression string and values for it. Adjusted to a dynamic query as per guidelines on https://www.drupal.org/docs/8/api/database-api/dynamic-queries/introduction-to-dynamic-queries and this now works again.

Convert static query into dynamic query to better manage placeholders and expressions

---

web/modules/custom/dept_migrate/src/MigrateUuidLookupManager.php

Small PHP 8.2 syntax tweak and a final attempt to load looked up media as types like remote video don't use the same properties or tables as the other types. This ensures embedded media is coverted correctly by the mediawysiwygfilter plugin.

Add final catch-all for loading remote video media

---

web/modules/custom/dept_sitemap/dept_sitemap.module

- Past, single update query didn't capture the dept prefix. Fixes this.
- REGEX_REPLACE unfortunately also affects the namespaces for the XML docs so we need to selectively patch that up, or the documents don't render

More detailed pass/replacements for dept sitemap namespace URLs across indexes and pages

---

config/sync/field.field.node.application.field_domain_source.yml
config/sync/field.field.node.article.field_domain_source.yml
config/sync/field.field.node.book.field_domain_source.yml
config/sync/field.field.node.contact.field_domain_source.yml
config/sync/field.field.node.featured_content_list.field_domain_source.yml
config/sync/field.field.node.gallery.field_domain_source.yml
config/sync/field.field.node.global_page.field_domain_source.yml
config/sync/field.field.node.heritage_site.field_domain_source.yml
config/sync/field.field.node.link.field_domain_source.yml
config/sync/field.field.node.page.field_domain_source.yml
config/sync/field.field.node.profile.field_domain_source.yml
config/sync/field.field.node.protected_area.field_domain_source.yml
config/sync/field.field.node.publication.field_domain_source.yml
config/sync/field.field.node.subtopic.field_domain_source.yml
config/sync/field.field.node.topic.field_domain_source.yml
config/sync/field.field.node.ual.field_domain_source.yml
config/sync/field.field.node.webform.field_domain_source.yml

Turn this off and it means a node shared to a domain can be seen on that domain, instead of redirecting to the hostname defined from the domain source field value.

Disable link rewrite/redirect for node canonical paths

---

migrate-scripts/migrate.sh

Very weird outcome but is repeatable locally. Once merged, source_row_status needs to be set to 1 for all node types in the map tables in order to ensure they're up to date again.

Omit config import step as it appears to alter how active migrate config operates despite having the same definition

---

web/modules/custom/dept_topics/src/Form/ManageTopicContentForm.php

What comes back to the form appears to be a canonical path instead of an absolute path. Adjusted validation to validate if there's not a canonical node path matched.

DEPT-759 manage content AJAX matcher dialog

---

composer.json
composer.lock

Patch applies cleanly, but introduces duplicate class properties which triggers a fatal runtime error. We've already got these class properties defined as per https://www.drupal.org/files/issues/2024-02-25/3336646-48.patch and the facets pages load with no log warnings or db log entries.

Remove facets patch (surplus to requirement, causes runtime error)

---

composer.json
composer.lock
config/sync/core.extension.yml
web/modules/custom/dept_book/dept_book.info.yml
web/modules/custom/dept_book/dept_book.module
web/modules/custom/dept_core/dept_core.module

Book module expires 'bid:123' style keys, but not the related node tag meaning changes aren't reflected right away when adjusting a book outline.
Had to shoehorn in a small patch to core to get this to work as post-submit handlers didn't seem to work. Doubled up with suitable, related cache tags added to the book nav block and expirations on the book outline removal form, too.

DEPT-780 refactor and adjust cache busting when book outline changes or content is removed

---

web/sites/default/settings.php

**Drush**
- Config import runs out of memory with drush; seems quite greedy but only used once or twice during deployments.
- Migrate status quite greedy too but used very infrequently.
**Node forms**
- DAERA topics tree is larger than others and with other page widgets it needs around 160M vs 130M for Finance. Giving it a comfortable bit of headroom here.
- Path limited to ensure this doesn't enable PSH burst mode for memory for every request. Sadly can't use route names here as the container isn't available early on in request handling phase.

Tweak memory limit over baseline config for drush commands and node forms

---

web/modules/custom/dept_homepage/dept_homepage.info.yml
web/modules/custom/dept_homepage/dept_homepage.libraries.yml
web/modules/custom/dept_homepage/dept_homepage.module
web/modules/custom/dept_homepage/js/normalise_base_url.js

Clientside workaround that checks the paths of any absolute links in the toolbar, except the 'Sites' menu. If any absolute links are found then they're replaced with values using the current site's hostname.
NB: this should be managed by domain/domain_source modules but due to some very opaque issues with the way cache items are generated, keyed and re-used in those modules the default domain sometimes is used for the <front> route path. Not a lot we can do server side to preprocess this owing to the way route paths are cached and altered by domain_source module. Even altering the toolbar render element doesn't seem to work around the issue. This could, potentially, pop up in other cases where something might need an absolute URL to the current department's front page but in those …

Attach custom JS to toolbar render element to fix hostname discrepancies

---

web/modules/custom/dept_core/dept_core.module

Admins can still remove the file but regular users will be encourage to delete the containing media entity to avoid orphaned content being created.

Remove file remove button for non-admin users to encourage media entity deletion

---

config/sync/domain.record.communities.yml
config/sync/domain.record.daera.yml
config/sync/domain.record.economy.yml
config/sync/domain.record.education.yml
config/sync/domain.record.executiveoffice.yml
config/sync/domain.record.health.yml
config/sync/domain.record.infrastructure.yml
config/sync/domain.record.justice.yml
config/sync/domain.record.nigov.yml

When launching a site, you'll want to remove the entry in config/production to avoid replacing the live hostname with a PSH hostname used for production/pre-launch

Add www. prefix to all live dept hostnames

---

web/robots.txt

Tested with https://technicalseo.com/tools/robots-txt/
Allowed: https://www.finance-ni.gov.uk/news?page=1
Disallowed: https://www.finance-ni.gov.uk/news?f%5B0%5D=topic%3A412572&f%5B1%5D=topic%3A412572

Robots.txt - disallow facet urls

---

config/sync/migrate_plus.migration.users.yml
web/modules/custom/dept_migrate/modules/dept_migrate_users/config/install/migrate_plus.migration.users.yml

Appears to sometimes happen when a user moves department, eg uid 1232 (moved from daera to health according to email addresses)

Skip users that already exist in D10

---

web/modules/custom/dept_core/src/Entity/Department.php

This appears to be redundant as the underlying hostname() call makes use of the config override in there.

Rely on config override for PSH URL

---

config/sync/domain_source.settings.yml
config/sync/field.field.user.user.field_domain_source.yml

Means admins can edit users on the currently logged in domain instead of having to log in to the other dept first. Only affects user entities to aid in making the user listing more easy to use

Skip canonical user entity path rewriting

---

config/sync/user.role.authenticated.yml
web/modules/custom/dept_core/dept_core.module

Permits non-admin users to see the department exposed filter. Domain access otherwise will hide the options

Allow authenticated users to view registered/active domains

---

config/sync/filter.format.basic_html.yml
config/sync/filter.format.full_html.yml
web/themes/custom/nicsdru_dept_theme/templates/block/block.html.twig
web/themes/custom/nicsdru_dept_theme/templates/block/facets-summary-item-list.html.twig
web/themes/custom/nicsdru_dept_theme/templates/field/field--node--field-summary--search-metadata.html.twig

Move media filter to fix additional tag issues
Search pages
- Remove novalidate tag from divs (this should only be on forms)
- Add `<li>` tags between two levels of `<ul>` tags on facet summary
- Add closing `<ul>` tag at the end of the facet summary
- Remove aria-describedby from the facet-summary as it wasn't pointing to anything on the page
- Output plaintext for card-content as there were multiple `<p>` tags being output unnecessarily

DEPT-923 ~ Fix HTML Validation issues

---

config/sync/core.entity_form_display.user.user.default.yml
config/sync/core.entity_view_display.user.user.full.yml

Lists the depts a user can access and groups the user form fields more sensibly.
Result:
Could perhaps benefit from further improvement to bring tasks/tabs to the template to aid editing or other tasks.

Improve user profile display page

---

config/sync/core.entity_view_display.media.document.media_library.yml
config/sync/core.entity_view_display.media.image.media_library.yml
config/sync/core.entity_view_display.media.remote_video.media_library.yml
config/sync/core.entity_view_display.media.video.media_library.yml
config/sync/responsive_image.styles.media_library_thumbnail.yml

Responsive image formatters considerably improve first render times making test timeouts much less of an issue than they were without compromising the end user experience.

DEPT-1037 improve media library ui performance

---

config/sync/search_api.index.consultations_index.yml
config/sync/search_api.index.news_index.yml
config/sync/search_api.index.publications_index.yml
config/sync/views.view.content_by_site_subtopic.yml
config/sync/views.view.news.yml
config/sync/views.view.news_search.yml

Granularity on the date field in Solr doesn't seem sufficient to go past day comparison, so we introduce the changed timestamp to improve on this (for now) until some improvement can be made on Solr date handling (or views consumption of that data)

Use changed property to improve natural sorting on content using publication date field

---

config/sync/core.entity_view_display.media.remote_video.default.yml

When embedding the default view mode seems to be used. Perhaps shouldn't but for now exclude the domain related fields from appearing at the front-end

Exclude domain fields from front-end render
